package dev.tiar.mangacat.items

/**
 * Created by Tiar on 03.2018.
 */
class ItemUrls {
    companion object {
        const val NhentaiHome = "https://nhentai.net/api/galleries/all"
        const val NhentaiSearch = "https://nhentai.net/api/galleries/search?query="
        const val NhentaiTags = "https://nhentai.net/api/galleries/tagged?tag_id="

        const val HentaiChanHome = "http://hentai-chan.me/manga/new"
        const val HentaiChanSearch = "http://hentai-chan.me/?do=search&subaction=search&story="
        const val HentaiChanTags = "http://hentai-chan.me/tags/"

        const val NudeMoonHome = "http://nude-moon.com/all_manga"
        const val NudeMoonSearch = "http://nude-moon.com/search?stext="
        const val NudeMoonTags = "http://nude-moon.com/tag/"

        val NudeMoonTagsTitle = arrayOf(
                "анал",
                "без цензуры",
                "беременные",
                "большие груди",
                "в бассейне",
                "в больнице",
                "в ванной",
                "в общественном месте",
                "в первый раз",
                "в транспорте",
                "в туалете",
                "гарем",
                "гипноз",
                "горничные",
                "горячий источник",
                "групповой секс",
                "драма",
                "запредельное",
                "золотой дождь",
                "извращение",
                "измена",
                "имеют парня",
                "инцест",
                "клизма",
                "колготки",
                "комиксы",
                "комиксы 3D",
                "косплей",
                "мамочки",
                "мастурбация",
                "много спермы",
                "молоко",
                "монстры",
                "на природе",
                "обычный секс",
                "огромный член",
                "пляж",
                "подглядывание",
                "принуждение",
                "проституция",
                "пьяные",
                "рабыни",
                "романтика",
                "с ушками",
                "секс игрушки",
                "спящие",
                "страпон",
                "студенты",
                "суккуб",
                "тентакли",
                "толстушки",
                "трапы",
                "ужасы",
                "униформа",
                "учитель и ученик",
                "фемдом",
                "фетиш",
                "фурри",
                "футанари",
                "футфетиш",
                "фэнтези",
                "цветная",
                "чикан",
                "чулки",
                "шимейл",
                "эксгибиционизм",
                "юмор",
                "юри",
                "яой",
                "ahegao",
                "BDSM",
                "ganguro",
                "gender bender",
                "megane",
                "monstergirl",
                "netorare",
                "nipple penetration",
                "titsfuck",
                "x-ray"
        )

        val NudeMoonTagsID = arrayOf(
                "анал",
                "без_цензуры",
                "беременные",
                "большие_груди",
                "в_бассейне",
                "в_больнице",
                "в_ванной",
                "в_общественном_месте",
                "в_первый_раз",
                "в_транспорте",
                "в_туалете",
                "гарем",
                "гипноз",
                "горничные",
                "горячий_источник",
                "групповой_секс",
                "драма",
                "запредельное",
                "золотой_дождь",
                "извращение",
                "измена",
                "имеют_парня",
                "инцест",
                "клизма",
                "колготки",
                "комиксы",
                "комиксы_3D",
                "косплей",
                "мамочки",
                "мастурбация",
                "много_спермы",
                "молоко",
                "монстры",
                "на_природе",
                "обычный_секс",
                "огромный_член",
                "пляж",
                "подглядывание",
                "принуждение",
                "проституция",
                "пьяные",
                "рабыни",
                "романтика",
                "с_ушками",
                "секс_игрушки",
                "спящие",
                "страпон",
                "студенты",
                "суккуб",
                "тентакли",
                "толстушки",
                "трапы",
                "ужасы",
                "униформа",
                "учитель_и_ученик",
                "фемдом",
                "фетиш",
                "фурри",
                "футанари",
                "футфетиш",
                "фэнтези",
                "цветная",
                "чикан",
                "чулки",
                "шимейл",
                "эксгибиционизм",
                "юмор",
                "юри",
                "яой",
                "ahegao",
                "BDSM",
                "ganguro",
                "gender_bender",
                "megane",
                "monstergirl",
                "netorare",
                "nipple_penetration",
                "titsfuck",
                "x-ray"
        )

        val HentaiChanTagsTitle = arrayOf(
                "3D",
                "action",
                "ahegao",
                "bdsm",
                "footfuck",
                "gender bender",
                "live",
                "lolcon",
                "megane",
                "mind break",
                "monstergirl",
                "netorare",
                "netori",
                "nipple penetration",
                "paizuri (titsfuck)",
                "rpg",
                "scat",
                "shooter",
                "simulation",
                "tomboy",
                "алкоголь",
                "анал",
                "андроид",
                "анилингус",
                "аркада",
                "арт",
                "без текста",
                "без трусиков",
                "без цензуры",
                "беременность",
                "бикини",
                "близнецы",
                "боди-арт",
                "больница",
                "большая грудь",
                "большие попки",
                "буккаке",
                "в ванной",
                "в общественном месте",
                "в первый раз",
                "в цвете",
                "в школе",
                "веб",
                "вибратор",
                "визуальная новелла",
                "волосатые женщины",
                "гаремник",
                "гипноз",
                "глубокий минет",
                "горячий источник",
                "групповой секс",
                "гяру и гангуро",
                "двойное проникновение",
                "девочки волшебницы",
                "девушка туалет",
                "демоны",
                "дилдо",
                "драма",
                "дыра в стене",
                "жестокость",
                "зомби",
                "зрелые женщины",
                "измена",
                "изнасилование",
                "инопланетяне",
                "инцест",
                "исполнение желаний",
                "камера",
                "квест",
                "колготки",
                "комиксы",
                "косплей",
                "купальники",
                "латекс и кожа",
                "магия",
                "маленькая грудь",
                "мастурбация",
                "мейдочки",
                "мерзкий дядька",
                "много девушек",
                "молоко",
                "монстры",
                "мочеиспускание",
                "мужская озвучка",
                "на природе",
                "наблюдение",
                "непрямой инцест",
                "огромная грудь",
                "огромный член",
                "остановка времени",
                "парень пассив",
                "переодевание",
                "песочница",
                "пляж",
                "подглядывание",
                "подчинение",
                "похищение",
                "принуждение",
                "прозрачная одежда",
                "психические отклонения",
                "публично",
                "рабыни",
                "романтика",
                "сверхъестественное",
                "секс игрушки",
                "сетакон",
                "спортивная форма",
                "спящие",
                "страпон",
                "темнокожие",
                "тентакли",
                "толстушки",
                "трап",
                "учитель и ученик",
                "ушастые",
                "фантазии",
                "фантастика",
                "фемдом",
                "фестиваль",
                "фистинг",
                "фурри",
                "футанари",
                "футанари имеет парня",
                "фэнтези",
                "хоррор",
                "цундере",
                "чикан",
                "чирлидеры",
                "чулки",
                "школьники",
                "школьницы",
                "школьный купальник",
                "эксгибиционизм",
                "эльфы",
                "эччи",
                "юмор",
                "юри",
                "яндере",
                "яой"
        )

        val HentaiChanTagsID = arrayOf(
                "3D",
                "action",
                "ahegao",
                "bdsm",
                "footfuck",
                "gender_bender",
                "live",
                "lolcon",
                "megane",
                "mind_break",
                "monstergirl",
                "netorare",
                "netori",
                "nipple_penetration",
                "paizuri_(titsfuck)",
                "rpg",
                "scat",
                "shooter",
                "simulation",
                "tomboy",
                "алкоголь",
                "анал",
                "андроид",
                "анилингус",
                "аркада",
                "арт",
                "без_текста",
                "без_трусиков",
                "без_цензуры",
                "беременность",
                "бикини",
                "близнецы",
                "боди-арт",
                "больница",
                "большая_грудь",
                "большие_попки",
                "буккаке",
                "в_ванной",
                "в_общественном_месте",
                "в_первый_раз",
                "в_цвете",
                "в_школе",
                "веб",
                "вибратор",
                "визуальная_новелла",
                "волосатые_женщины",
                "гаремник",
                "гипноз",
                "глубокий_минет",
                "горячий_источник",
                "групповой_секс",
                "гяру_и_гангуро",
                "двойное_проникновение",
                "девочки_волшебницы",
                "девушка_туалет",
                "демоны",
                "дилдо",
                "драма",
                "дыра_в_стене",
                "жестокость",
                "зомби",
                "зрелые_женщины",
                "измена",
                "изнасилование",
                "инопланетяне",
                "инцест",
                "исполнение_желаний",
                "камера",
                "квест",
                "колготки",
                "комиксы",
                "косплей",
                "купальники",
                "латекс_и_кожа",
                "магия",
                "маленькая_грудь",
                "мастурбация",
                "мейдочки",
                "мерзкий_дядька",
                "много_девушек",
                "молоко",
                "монстры",
                "мочеиспускание",
                "мужская_озвучка",
                "на_природе",
                "наблюдение",
                "непрямой_инцест",
                "огромная_грудь",
                "огромный_член",
                "остановка_времени",
                "парень_пассив",
                "переодевание",
                "песочница",
                "пляж",
                "подглядывание",
                "подчинение",
                "похищение",
                "принуждение",
                "прозрачная_одежда",
                "психические_отклонения",
                "публично",
                "рабыни",
                "романтика",
                "сверхъестественное",
                "секс_игрушки",
                "сетакон",
                "спортивная_форма",
                "спящие",
                "страпон",
                "темнокожие",
                "тентакли",
                "толстушки",
                "трап",
                "учитель_и_ученик",
                "ушастые",
                "фантазии",
                "фантастика",
                "фемдом",
                "фестиваль",
                "фистинг",
                "фурри",
                "футанари",
                "футанари_имеет_парня",
                "фэнтези",
                "хоррор",
                "цундере",
                "чикан",
                "чирлидеры",
                "чулки",
                "школьники",
                "школьницы",
                "школьный_купальник",
                "эксгибиционизм",
                "эльфы",
                "эччи",
                "юмор",
                "юри",
                "яндере",
                "яой"
        )

        val NhentaiTagsTitle = arrayOf(
            "3d",
            "abortion",
            "absorption",
            "age progression",
            "age regression",
            "ahegao",
            "ahru",
            "aji ponntarou",
            "akigami satoru",
            "a kyokufuri",
            "alem gakan",
            "alien",
            "alien girl",
            "all the way through",
            "already uploaded",
            "amano jyaku",
            "amputee",
            "anal",
            "anal birth",
            "anchuu mosaku",
            "angel",
            "anorexic",
            "anthology",
            "apron",
            "arekishi raiho",
            "armpit licking",
            "armpit sex",
            "artbook",
            "artistcg",
            "asphyxiation",
            "ass expansion",
            "assjob",
            "aunt",
            "autofellatio",
            "autopaizuri",
            "bald",
            "balljob",
            "balls expansion",
            "ball sucking",
            "bandages",
            "bandaid",
            "bankoku ayuya",
            "bbm",
            "bbw",
            "bdsm",
            "bear",
            "beauty mark",
            "bee girl",
            "bestiality",
            "big areolae",
            "big ass",
            "big balls",
            "big breasts",
            "big clit",
            "big lips",
            "big nipples",
            "big penis",
            "big vagina",
            "bike shorts",
            "bikini",
            "birth",
            "bisexual",
            "blackmail",
            "blind",
            "blindfold",
            "blood",
            "bloomers",
            "blowjob",
            "blowjob face",
            "body modification",
            "body painting",
            "bodystocking",
            "bodysuit",
            "body swap",
            "body writing",
            "bondage",
            "brain fuck",
            "breast expansion",
            "breast feeding",
            "bride",
            "brother",
            "bukkake",
            "bull",
            "bunny boy",
            "bunny girl",
            "business suit",
            "butler",
            "cannibalism",
            "cashier",
            "catboy",
            "catfight",
            "catgirl",
            "cbt",
            "centaur",
            "cervix penetration",
            "chastity belt",
            "cheating",
            "cheerleader",
            "chikan",
            "chinese dress",
            "chiyou yoyuchi",
            "chloroform",
            "christmas",
            "clamp",
            "clit growth",
            "clothed paizuri",
            "coach",
            "collar",
            "compilation",
            "condom",
            "coprophagia",
            "corruption",
            "corset",
            "cosplaying",
            "cousin",
            "cowgirl",
            "cowman",
            "crocodile ave",
            "crossdressing",
            "crotch tattoo",
            "crown",
            "cum bath",
            "cum in eye",
            "cum swap",
            "cunnilingus",
            "cuntboy",
            "dark nipples",
            "dark sclera",
            "dark skin",
            "daughter",
            "deepthroat",
            "defloration",
            "demon",
            "demon girl",
            "diaper",
            "dibi",
            "dickgirl on dickgirl",
            "dickgirl on male",
            "dickgirls only",
            "dick growth",
            "dicknipples",
            "dilf",
            "dog",
            "dog boy",
            "dog girl",
            "doll joints",
            "double anal",
            "double blowjob",
            "double penetration",
            "double vaginal",
            "dougi",
            "dragon",
            "drugs",
            "drunk",
            "ear fuck",
            "eel",
            "eggs",
            "electric shocks",
            "elf",
            "emotionless sex",
            "enema",
            "entokkun",
            "exhibitionism",
            "eyemask",
            "eyepatch",
            "eye penetration",
            "facesitting",
            "fairy",
            "farting",
            "father",
            "females only",
            "femdom",
            "feminization",
            "ffm threesome",
            "fft threesome",
            "filming",
            "fingering",
            "first person perspective",
            "fisting",
            "foot insertion",
            "footjob",
            "foot licking",
            "forbidden content",
            "forniphilia",
            "fox boy",
            "fox girl",
            "freckles",
            "frog",
            "frottage",
            "full body tattoo",
            "full censorship",
            "full color",
            "fundoshi",
            "furry",
            "futanari",
            "gag",
            "gaping",
            "garter belt",
            "gasmask",
            "gender bender",
            "ghost",
            "giant",
            "giantess",
            "gigantic breasts",
            "glasses",
            "glory hole",
            "goblin",
            "gokkun",
            "gorilla",
            "gothic lolita",
            "granddaughter",
            "grandmother",
            "great akuta",
            "group",
            "growth",
            "guro",
            "gyaru",
            "gyaru-oh",
            "gymshorts",
            "hairjob",
            "hairy",
            "hairy armpits",
            "haise sasaki",
            "handicapped",
            "handjob",
            "harem",
            "harpy",
            "haruharu dou",
            "heterochromia",
            "horse",
            "horse boy",
            "hotpants",
            "huge breasts",
            "huge penis",
            "human cattle",
            "human on furry",
            "human pet",
            "humiliation",
            "imageset",
            "impregnation",
            "incest",
            "incomplete",
            "infantilism",
            "inflation",
            "insect",
            "insect girl",
            "inseki",
            "inverted nipples",
            "invisible",
            "ishoku dougen",
            "josou seme",
            "kabashima akira",
            "kakucho parts",
            "kappa",
            "kazefuki poni",
            "kemonomimi",
            "kimono",
            "kindergarten uniform",
            "kirakou",
            "kissing",
            "kiyomiya ryou",
            "kobayashi yutaka",
            "koborii",
            "kugami annin",
            "kunoichi",
            "lab coat",
            "lactation",
            "large insertions",
            "latex",
            "layer cake",
            "leg lock",
            "leonard 16 sei",
            "leotard",
            "levi",
            "lingerie",
            "living clothes",
            "lizard girl",
            "lolicon",
            "long tongue",
            "low bestiality",
            "low lolicon",
            "low shotacon",
            "machine",
            "magical girl",
            "maid",
            "male on dickgirl",
            "males only",
            "manboorerere",
            "maruko rondo",
            "mashi miyuki",
            "mashumaro maron",
            "masked face",
            "masturbation",
            "matsuzaka takeshi",
            "mature",
            "mecha girl",
            "menstruation",
            "mermaid",
            "merman",
            "metal armor",
            "midget",
            "miki hime",
            "miko",
            "mikoshiro nagitoh",
            "milf",
            "military",
            "milking",
            "mind break",
            "mind control",
            "mine mura",
            "minigirl",
            "miniguy",
            "minotaur",
            "misakitou",
            "misc",
            "missing cover",
            "miyamoto smoke",
            "mmf threesome",
            "mmt threesome",
            "monkey",
            "monster",
            "monster girl",
            "moral degeneration",
            "moriyama toh",
            "mosaic censorship",
            "mother",
            "mouse girl",
            "mtf threesome",
            "multiple arms",
            "multiple breasts",
            "multiple paizuri",
            "multiple penises",
            "multi-work series",
            "muscle",
            "nakadashi",
            "narumeia",
            "navel fuck",
            "nazi",
            "necrophilia",
            "netorare",
            "niece",
            "ninja",
            "nipple birth",
            "nipple expansion",
            "nipple fuck",
            "non-h",
            "nose fuck",
            "nose hook",
            "noto kurumi",
            "nudity only",
            "nuenya",
            "nun",
            "nurse",
            "octopus",
            "oguni yoshinobu",
            "oil",
            "old man",
            "onahole",
            "oni",
            "oppai loli",
            "orc",
            "orgasm denial",
            "out of order",
            "oyakodon",
            "paizuri",
            "pantyhose",
            "pantyjob",
            "parasite",
            "pasties",
            "pegging",
            "petrification",
            "phimosis",
            "phone sex",
            "piercing",
            "pig",
            "pig girl",
            "pig man",
            "pillory",
            "pirate",
            "piss drinking",
            "plant girl",
            "pole dancing",
            "policeman",
            "policewoman",
            "ponygirl",
            "poor grammar",
            "possession",
            "pregnant",
            "prehensile hair",
            "priest",
            "prolapse",
            "prostate massage",
            "prostitution",
            "pubic stubble",
            "public use",
            "raccoon girl",
            "race queen",
            "randoseru",
            "rando seru",
            "rape",
            "replaced",
            "rimjob",
            "robot",
            "ryona",
            "ryuta amazume",
            "saliva",
            "sample",
            "scanmark",
            "scar",
            "scat",
            "schoolboy uniform",
            "schoolgirl uniform",
            "school swimsuit",
            "scrotal lingerie",
            "selfcest",
            "sex toys",
            "shared senses",
            "shaved head",
            "sheep girl",
            "shemale",
            "shibari",
            "shimapan",
            "shimon ryuushirou",
            "shinozuka jouji",
            "shin seidou honpo",
            "shirano jin",
            "shirono mahiro",
            "shotacon",
            "shrinking",
            "shuhan",
            "shuudan bouryoku",
            "sister",
            "skinsuit",
            "slave",
            "sleeping",
            "slime",
            "slime girl",
            "slug",
            "small breasts",
            "smegma",
            "smell",
            "smoking",
            "snake",
            "snake girl",
            "snuff",
            "sole dickgirl",
            "sole female",
            "sole male",
            "solo action",
            "spanking",
            "speculum",
            "spider girl",
            "squid girl",
            "squirrel girl",
            "squirting",
            "ssbbw",
            "stewardess",
            "stockings",
            "stomach deformation",
            "story arc",
            "strap-on",
            "stretching",
            "stuck in wall",
            "sumata",
            "sundress",
            "sunglasses",
            "sweating",
            "swimsuit",
            "swinging",
            "syringe",
            "table masturbation",
            "tailjob",
            "tail plug",
            "takuji",
            "tall girl",
            "tall man",
            "tankoubon",
            "tanlines",
            "teacher",
            "tentacles",
            "testa chuubou",
            "the jinshan",
            "the seven deadly sins",
            "thigh high boots",
            "tiara",
            "tickling",
            "tights",
            "time stop",
            "tomboy",
            "tomgirl",
            "torture",
            "tracksuit",
            "trampling",
            "transformation",
            "tribadism",
            "triple anal",
            "triple penetration",
            "triple vaginal",
            "tsukimi daifuku",
            "ttf threesome",
            "ttm threesome",
            "tube",
            "tuna empire",
            "tutor",
            "twins",
            "unbirth",
            "uncensored",
            "uncle",
            "underwater",
            "unizou",
            "unusual pupils",
            "unusual teeth",
            "urethra insertion",
            "urination",
            "uso seisakujo",
            "vacbed",
            "vaginal sticker",
            "vampire",
            "virginity",
            "vomit",
            "vore",
            "voyeurism",
            "waiter",
            "waitress",
            "watermarked",
            "webtoon",
            "weight gain",
            "western",
            "wet clothes",
            "whip",
            "widow",
            "wings",
            "witch",
            "wolf",
            "wolf boy",
            "wolf girl",
            "wooden horse",
            "worm",
            "wormhole",
            "wrestling",
            "x-ray",
            "yakan",
            "yandere",
            "yaoi",
            "yuki kagerou",
            "yukino tsukimi",
            "yuri",
            "zombie")
        val NhentaiTagsID = arrayOf(
            "80551",
            "15959",
            "15215",
            "26898",
            "31986",
            "13989",
            "54794",
            "54306",
            "55852",
            "54436",
            "54294",
            "17967",
            "30839",
            "18420",
            "53449",
            "57228",
            "7354",
            "14283",
            "21924",
            "91",
            "24115",
            "16224",
            "10988",
            "24726",
            "54774",
            "25296",
            "7684",
            "27378",
            "16759",
            "15471",
            "26366",
            "23073",
            "23035",
            "33032",
            "5109",
            "73750",
            "15532",
            "13057",
            "27530",
            "2527",
            "32201",
            "56111",
            "31880",
            "7142",
            "1088",
            "2554",
            "81707",
            "24484",
            "12523",
            "23632",
            "9083",
            "19561",
            "2937",
            "30126",
            "3811",
            "7995",
            "30555",
            "20769",
            "21538",
            "19175",
            "706",
            "36957",
            "29182",
            "1663",
            "31012",
            "22221",
            "28800",
            "29859",
            "15225",
            "11376",
            "4738",
            "15347",
            "24412",
            "11089",
            "31846",
            "15658",
            "16554",
            "23183",
            "10794",
            "24529",
            "18322",
            "26953",
            "7019",
            "14280",
            "23132",
            "370",
            "12220",
            "30848",
            "14526",
            "7208",
            "27234",
            "31386",
            "28349",
            "21259",
            "9661",
            "3455",
            "9260",
            "25744",
            "32745",
            "24450",
            "57339",
            "23965",
            "30811",
            "75320",
            "31280",
            "72139",
            "13515",
            "31044",
            "7584",
            "12824",
            "16518",
            "4573",
            "7372",
            "17531",
            "19390",
            "24708",
            "31453",
            "56909",
            "15782",
            "51399",
            "28897",
            "24555",
            "23422",
            "369",
            "7155",
            "12031",
            "7735",
            "52826",
            "19018",
            "29399",
            "32996",
            "20525",
            "26380",
            "16228",
            "22967",
            "54985",
            "35970l",
            "35968",
            "72471",
            "30645",
            "31783",
            "29013",
            "10604",
            "984",
            "15119",
            "4566",
            "5620",
            "10685",
            "22945",
            "10811",
            "10693",
            "8119",
            "22079",
            "24764",
            "23660",
            "28166",
            "32224",
            "9908",
            "832",
            "8516",
            "9406",
            "54430",
            "19899",
            "15712",
            "24933",
            "16368",
            "13136",
            "30472",
            "4935",
            "6898",
            "8050",
            "15408",
            "32589",
            "15348",
            "20439",
            "27063",
            "26130",
            "31173",
            "32602",
            "7657",
            "20282",
            "17752",
            "53474",
            "1814",
            "4459",
            "31285",
            "14138",
            "24410",
            "13640",
            "21112",
            "8368",
            "20905",
            "3843",
            "6834",
            "779",
            "4435",
            "25996",
            "3666",
            "10261",
            "30035",
            "17676",
            "5434",
            "28335",
            "80498",
            "8378",
            "4068",
            "8400",
            "25766",
            "18946",
            "25949",
            "33138",
            "11020",
            "55567",
            "8010",
            "18544",
            "27217",
            "25050",
            "20362",
            "5452",
            "19592",
            "16828",
            "28426",
            "54297",
            "27038",
            "1033",
            "15785",
            "10429",
            "54847",
            "38066",
            "16947",
            "8254",
            "28589",
            "14072",
            "23967",
            "25848",
            "36616",
            "21774",
            "5357",
            "29076",
            "29224",
            "22942",
            "31101",
            "11727",
            "21989",
            "24621",
            "13613",
            "1067",
            "29631",
            "19455",
            "56259",
            "50390",
            "57642",
            "54778",
            "31313",
            "32964",
            "81774",
            "17773",
            "80631",
            "75369",
            "1643",
            "54435",
            "55981",
            "19318",
            "23749",
            "31337",
            "15242",
            "24102",
            "28778",
            "20074",
            "6671",
            "2633",
            "53507",
            "27697",
            "4253",
            "25871",
            "11073",
            "31488",
            "19440",
            "23917",
            "21822",
            "14362",
            "27598",
            "8429",
            "7838",
            "190",
            "35971",
            "21712",
            "81172",
            "24498",
            "56133",
            "80492",
            "21283",
            "9162",
            "54929",
            "8860",
            "31371",
            "31663",
            "26822",
            "21903",
            "11399",
            "12154",
            "54027",
            "6900",
            "56116",
            "1207",
            "18613",
            "10354",
            "27384",
            "20617",
            "54756",
            "21450",
            "29347",
            "18447",
            "54433",
            "19721",
            "49646",
            "55042",
            "7256",
            "31744",
            "27531",
            "18567",
            "7550",
            "13722",
            "56328",
            "27473",
            "15853",
            "19443",
            "15463",
            "23639",
            "4526",
            "20120",
            "11276",
            "21572",
            "30473",
            "13720",
            "54817",
            "29579",
            "21513",
            "22411",
            "8653",
            "15045",
            "5172",
            "7063",
            "1327",
            "19479",
            "23225",
            "4678",
            "28119",
            "55522",
            "80978",
            "80555",
            "3391",
            "6525",
            "20372",
            "55005",
            "15749",
            "2956",
            "3947",
            "1037",
            "25663",
            "6220",
            "24984",
            "32538",
            "50505",
            "25614",
            "24380",
            "7942",
            "29001",
            "10606",
            "5200",
            "30176",
            "17501",
            "29481",
            "5820",
            "22862",
            "19426",
            "11914",
            "23921",
            "22149",
            "32282",
            "920",
            "24168",
            "24427",
            "20789",
            "11968",
            "20170",
            "25457",
            "6343",
            "27977",
            "19737",
            "22025",
            "9990",
            "12695",
            "19064",
            "8391",
            "26471",
            "4742",
            "31687",
            "56701",
            "27553",
            "11941",
            "24676",
            "17591",
            "14069",
            "55213",
            "26609",
            "29957",
            "15492",
            "2452",
            "2820",
            "7752",
            "10314",
            "29565",
            "21127",
            "27120",
            "14971",
            "26830",
            "78262",
            "17476",
            "16236",
            "32752",
            "13468",
            "54324",
            "55862",
            "56279",
            "56451",
            "15265",
            "32341",
            "2695",
            "54783",
            "54808",
            "28031",
            "11247",
            "33129",
            "16533",
            "1352",
            "19171",
            "18692",
            "25601",
            "27720",
            "25822",
            "31997",
            "18409",
            "14010",
            "10542",
            "35972",
            "35762",
            "35763",
            "17801",
            "5962",
            "17003",
            "17005",
            "1008",
            "14870",
            "683",
            "80549",
            "26388",
            "24201",
            "32484",
            "8739",
            "5810",
            "17337",
            "28869",
            "24967",
            "266",
            "30895",
            "1590",
            "3735",
            "25085",
            "14418",
            "16262",
            "13672",
            "50486",
            "56379",
            "26952",
            "14573",
            "23237",
            "22950",
            "28550",
            "31775",
            "54642",
            "51421",
            "30760",
            "18328",
            "27112",
            "17800",
            "14321",
            "5936",
            "29366",
            "29023",
            "4549",
            "17349",
            "20488",
            "2531",
            "30206",
            "6303",
            "3614",
            "32870",
            "57927",
            "559",
            "24712",
            "28824",
            "34059",
            "13882",
            "560",
            "9116",
            "8693",
            "13993",
            "3031",
            "28374",
            "6817",
            "1215",
            "5529",
            "10476",
            "54372",
            "24053",
            "19354",
            "7577",
            "2515",
            "7288",
            "15425",
            "28521",
            "660",
            "26848",
            "30786",
            "50585",
            "16487",
            "19864",
            "50211",
            "20284",
            "25794",
            "2153",
            "7546",
            "10992",
            "1942",
            "14516",
            "16461",
            "9518",
            "3551",
            "23463",
            "20035",
            "80748",
            "31319",
            "23895",
            "55696",
            "80790",
            "19954",
            "571")
    }
}